#ifndef _DEFAULTS_H
#define _DEFAULTS_H

#define DEFAULT_HOSTNAME "UNKNOWN"
#define DEFAULT_HOSTNAME_LENGTH 8
#define DEFAULT_HOSTNAME_BUFFER_SIZE 1024
#define DEFAULT_PORT 6969
#define DEFAULT_THREAD_POOL_SIZE 2
#define DEFAULT_TIME_OUT 60

#endif
